<?php

/**
 * Implements hook_page_attachments().
 */
function diet_page_attachments(array &$attachments) {
  $route = \Drupal::routeMatch();
  $route_name = $route->getRouteName();
  $routes = ['node.add'];

  if (in_array($route_name, $routes)) {
    $node_bundle = $route->getParameter('node_type')->get('type');

    if ($node_bundle == 'diet_profile') {
      $attachments['#attached']['library'][] = 'diet/profile';
    }
  }
}
